language: python
sudo: false
cache:
  pip: true
  directories:
    - $TRAVIS_BUILD_DIR/buildout-cache
python:
  - 2.7
addons:
  apt:
    packages:
    - chromedriver
    - chromium
    - libpcre3
    - libpcre3-dev
    - libssl-dev
    - libexpat1-dev
    - gnuplot
    - libgdk-pixbuf2.0-0
before_script:
  - export DISPLAY=99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/buildout-cache/{eggs,downloads}
  - echo "[buildout]" > $TRAVIS_BUILD_DIR/default.cfg
  - echo "download-cache = $TRAVIS_BUILD_DIR/buildout-cache/downloads" >> $TRAVIS_BUILD_DIR/default.cfg
  - echo "eggs-directory = $TRAVIS_BUILD_DIR/buildout-cache/eggs" >> $TRAVIS_BUILD_DIR/default.cfg
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout
install:
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/test -m bika.lims --layer=bika.lims.testing.BikaTestingLayer:Functional
